### ISSUE TITLE
Validation error with new custom field

### ISSUE THREAD

**Issue by isotherm** [isotherm/python-manager-api#1]
Reported by [twodogzz](https://forum.manager.io/u/twodogzz) on the [Manager forum](https://forum.manager.io/t/python-module-for-manager-api/44900/18?u=isotherm):

> My code returns a validation error when trying to read the inventory data from the [Manager.io](http://manager.io/) API. The error message pydantic.error_wrappers.ValidationError: 1 validation error for InventoryItem indicates that there is an issue with the data returned by the API when trying to get an InventoryItem object.
> 
> The specific validation error CustomFields2 -> Decimals -> 973a30fe-448f-41e3-97ce-f2755c7e67fe none is not an allowed value (type=type_error.none.not_allowed) suggests that the value for the Decimals custom field with ID 973a30fe-448f-41e3-97ce-f2755c7e67fe is None, which is not an allowed value.

**Comment by twodogzz** [comment]
I'm using PyCharm GUI and Python version 3.11.4 with Manager Cloud version 23.12.9.1219.
The issue described doesn't occur with my latest "configuration".

However, retrieving custom field values is still a challenge with my little bit of code.
I tried using this statement to get the custom field value, _custom_field_value = itm.CustomFields.get('41bdc4fe-4ddd-4673-b77d-8a5d12f8d8e5', '')_ in the **for itm in items:** but only got an empty string returned.

I guess I'm trying to "get" the value directly from Manager API, when I should refer to the appropriate object in the "model"!
Okay, I must admit my Python programming skills are very basic... 

So, I did some digging into dictionary objects and added this gem! It works!
```python
for itm in items:
    for key, value in itm.CustomFields.items():
        if key:'41bdc4fe-4ddd-4673-b77d-8a5d12f8d8e5'
        custom_field_value = value
    listbox.insert(tk.END, f"{itm.ItemCode}, {itm.ItemName}, {itm.DefaultSalesUnitPrice}, {custom_field_value}, {itm.Key}")
```
Original code with my problem...
```python
from manager_api import Business
import tkinter as tk

# Open the business. NOTE: Always use a test business first!
business = Business("https://[your-manager-instance].manager.io", "[your-user]", "[your-password]", "[your-business]")

# Retrieve 50 Inventory Items
items = business.InventoryItem.list()[:50]

# Create a new tkinter window
root = tk.Tk()

# Create a scrollbar
scrollbar = tk.Scrollbar(root)
scrollbar.pack(side=tk.RIGHT, fill=tk.Y)

# Create a listbox with a specified width and height and attach the scrollbar
listbox = tk.Listbox(root, width=150, height=30, yscrollcommand=scrollbar.set)
for itm in items:
    custom_field_value = itm.CustomFields.get('41bdc4fe-4ddd-4673-b77d-8a5d12f8d8e5', '')
    listbox.insert(tk.END, f"{itm.ItemCode}, {itm.ItemName}, {itm.DefaultSalesUnitPrice}, {custom_field_value}, {itm.Key}")
listbox.pack(side=tk.LEFT, fill=tk.BOTH)

# Configure the scrollbar to scroll the listbox
scrollbar.config(command=listbox.yview)

# Start the tkinter main loop
root.mainloop()

```

**Comment by isotherm** [comment]
It looks like you have the right idea, however you should never need to refer to a GUID explicitly.

First, as part of setup, look up the custom field by its name. Custom fields are global across all object types. Then, use that custom field object as a key in a particular object (e.g. Item)'s CustomFields. Like this:
```
weight_field = business.CustomField["Weight"]
# ...
for itm in tiems:
    weight = itm.CustomFields[weight_field]
```

You can also use the same reference to add/update the field:
```
itm.CustomFields[weight_field] = 123
```

Since it sounds like everything is working for you now, I am closing this issue.

**Comment by twodogzz** [comment]
Hi Kirk,

I’m grateful for your assistance with my issue and letting me use your unbelievably complex python API. Just wanted to express my sincere appreciation for your talents and generosity.

Kind regards,
Wayne
Australia
